### PR TITLE
Moved serviced segment specification to config file

### PR DESCRIPTION
**Pull request by DarioValocchi**

### CODE REVIEW

**Comment by DarioValocchi** [comment]
test this please

**Comment by DarioValocchi** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Pull request merged**
